services:
  flask-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: always
